name: Release

on:
  push:
    branches:
      - master

jobs:
  release:
    if: github.repository == 'musy-app/musy-app'

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Use pnpm
        uses: pnpm/action-setup@v2.2.4
        with:
          version: 7

      - name: Use Node
        uses: actions/setup-node@v3
        with:
          cache: "pnpm"

      - name: Install Dependencies
        run: pnpm i

      - name: Lint
        run: pnpm lint

      - name: Build
        run: pnpm build

      - name: Creating .npmrc
        run: |
          cat << EOF > "$HOME/.npmrc"
            //npm.pkg.github.com/:_authToken=$NPM_TOKEN
          EOF
        env:
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release Pull Request or Publish to Github Packages
        uses: changesets/action@v1
        with:
          publish: pnpm run release
          version: pnpm run version
          commit: "🔖 release version"
          title: "🔖 release version"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
